baseURL: http://something-fresh.org/
languageCode: en-us
title: Hugo Fresh Theme
theme: hugo-fresh

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Meet Core at ICPA
    # Hero subtitle (optional)
    subtitle: Our new software is set to take the industry by storm. It's the first offender software in the world to focus on both prison and community corrections. Seeing is truly believing.

    # Hero image (from /images/___)
    image: illustrations/offender.png

 

    